name: Noosa Village Jewellers
favicon: null
layout_spectrum: 0.99687
typography_spectrum: 0.87371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050608'
    - '#d3d1d2'
    - '#112c3f'
    - '#727075'
  brandStrength: 1
  lightness: 0.05082254693843424
  saturation: 0.487572981743142
  rhythmicContrast: 0.2727324494626373
purpose: []
