name: Noosa Village Jewellers
favicon: null
layout_spectrum: 0.9342255510855466
typography_spectrum: 0.12202603579498827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.014840865507721901
  lightness: 0.05082254693843424
  saturation: 0.487572981743142
  rhythmicContrast: 0.2727324494626373
purpose: []
